/*
* $Copyright 2013-2017, Sierra Telecom, Inc.
* All Rights Reserved.
*
* This is UNPUBLISHED PROPRIETARY SOURCE CODE of Sierra Telecom, Inc.;
* the contents of this file may not be disclosed to third parties, copied
* or duplicated in any form, in whole or in part, without the prior
* written permission of Sierra Telecom, Inc.$
*/

/** @file sensors_def.c
*  Created on: Oct 27, 2019
*  Author: Auto Generated Code Do NOT Modify
*/

#include <stdint.h>
#include <stdbool.h>

#include "common.h"
#include "product.h"
#include "sensors.h"
#include "hal_ble_device_rssi_levels_2037468041.h"
#include "hal_co2_equivalent_2088797904.h"
#include "hal_humidity_342048076.h"
#include "hal_mass_concentration_pm_1_0_32791331.h"
#include "hal_mass_concentration_pm_10_0_734215216.h"
#include "hal_mass_concentration_pm_2_5_1698993330.h"
#include "hal_mass_concentration_pm_4_0_1858953557.h"
#include "hal_number_concentration_pm_0_5_1642774029.h"
#include "hal_number_concentration_pm_1_0_1984590476.h"
#include "hal_number_concentration_pm_10_0_1909326236.h"
#include "hal_number_concentration_pm_2_5_1751774023.h"
#include "hal_number_concentration_pm_4_0_891153645.h"
#include "hal_typical_particle_size_159299661.h"
#include "hal_particulate_matter_index_1695740845.h"
#include "hal_temperature_1913614964.h"
#include "hal_typical_particle_size_159299661.h"
#include "hal_voc_1189979747.h"

/******************************************************
*                      Macros
******************************************************/

/******************************************************
*                    Constants
******************************************************/
#define NULL		( 0x00 )
/******************************************************
*                   Enumerations
******************************************************/

/******************************************************
*                 Type Definitions
******************************************************/

/******************************************************
*                    Structures
******************************************************/

/******************************************************
*               Function Declarations
******************************************************/

/******************************************************
*               Variable Definitions
******************************************************/

const imx_control_sensor_block_t imx_sensors_defaults[ IMX_NO_SENSORS ]  = {
    {
        .name = "Host S/W Revision",
        .id = IMX_HOST_S_W_REVISION_103378620,
        .sample_rate = 0,
        .sample_batch_size = 1,
        .percent_change_to_send = 0,
        .enabled = 1,
        .read_only = 1,
        .poll_rate = 30000,
        .send_on_percent_change = 0,
        .data_type = IMX_VARIABLE_LENGTH,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .var_data = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "RF Scan",
        .id = IMX_RF_SCAN_123455660,
        .sample_rate = 0,
        .sample_batch_size = 1,
        .percent_change_to_send = 0,
        .enabled = 1,
        .read_only = 1,
        .poll_rate = 30000,
        .send_on_percent_change = 0,
        .data_type = IMX_VARIABLE_LENGTH,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .var_data = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Variable Data In",
        .id = IMX_VARIABLE_DATA_IN_2058836870,
        .sample_rate = 0,
        .sample_batch_size = 1,
        .percent_change_to_send = 0,
        .enabled = 1,
        .read_only = 1,
        .poll_rate = 30000,
        .send_on_percent_change = 0,
        .data_type = IMX_UINT32,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "WiFi BSSID",
        .id = IMX_WIFI_BSSID_173116155,
        .sample_rate = 0,
        .sample_batch_size = 1,
        .percent_change_to_send = 0,
        .enabled = 1,
        .read_only = 1,
        .poll_rate = 30000,
        .send_on_percent_change = 0,
        .data_type = IMX_VARIABLE_LENGTH,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .var_data = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "WiFi Channel",
        .id = IMX_WIFI_CHANNEL_173916172,
        .sample_rate = 0,
        .sample_batch_size = 1,
        .percent_change_to_send = 0,
        .enabled = 1,
        .read_only = 1,
        .poll_rate = 30000,
        .send_on_percent_change = 0,
        .data_type = IMX_UINT32,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "WiFi RF Noise",
        .id = IMX_WIFI_RF_NOISE_1248909411,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 0,
        .enabled = 1,
        .read_only = 1,
        .poll_rate = 30000,
        .send_on_percent_change = 0,
        .data_type = IMX_INT32,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "WiFi RSSI",
        .id = IMX_WIFI_RSSI_101600364,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 0,
        .enabled = 1,
        .read_only = 1,
        .poll_rate = 30000,
        .send_on_percent_change = 0,
        .data_type = IMX_INT32,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "BLE Device RSSI Levels",
        .id = BLE_DEVICE_RSSI_LEVELS_2037468041,
        .sample_rate = 30000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 60000,
        .send_on_percent_change = 0,
        .data_type = IMX_VARIABLE_LENGTH,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .var_data = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "CO2 Equivalent",
        .id = CO2_EQUIVALENT_2088797904,
        .sample_rate = 60000,
        .sample_batch_size = 5,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_UINT32,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Humidity",
        .id = HUMIDITY_342048076,
        .sample_rate = 60000,
        .sample_batch_size = 5,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_UINT32,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Mass Concentration PM 1.0",
        .id = MASS_CONCENTRATION_PM_1_0_32791331,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Mass Concentration PM 10.0",
        .id = MASS_CONCENTRATION_PM_10_0_734215216,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Mass Concentration PM 2.5",
        .id = MASS_CONCENTRATION_PM_2_5_1698993330,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Mass Concentration PM 4.0",
        .id = MASS_CONCENTRATION_PM_4_0_1858953557,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Number Concentration PM 0.5",
        .id = NUMBER_CONCENTRATION_PM_0_5_1642774029,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Number Concentration PM 1.0",
        .id = NUMBER_CONCENTRATION_PM_1_0_1984590476,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Number Concentration PM 10.0",
        .id = NUMBER_CONCENTRATION_PM_10_0_1909326236,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Number Concentration PM 2.5",
        .id = NUMBER_CONCENTRATION_PM_2_5_1751774023,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Number Concentration PM 4.0",
        .id = NUMBER_CONCENTRATION_PM_4_0_891153645,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Particulate Matter Index",
        .id = PARTICULATE_MATTER_INDEX_1695740845,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_UINT32,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Temperature",
        .id = TEMPERATURE_1913614964,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .float_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "Typical Particle Size",
        .id = TYPICAL_PARTICLE_SIZE_159299661,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_FLOAT,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    },
    {
        .name = "VOC",
        .id = VOC_1189979747,
        .sample_rate = 60000,
        .sample_batch_size = 15,
        .percent_change_to_send = 1,
        .enabled = 1,
        .read_only = 0,
        .poll_rate = 1000,
        .send_on_percent_change = 0,
        .data_type = IMX_UINT32,
        .set_default = 0,
        .send_imatrix = 1,
        .default_value = { .int_32bit = 0 },
        .use_warning_level_low = 0,
        .use_warning_level_high  = 0,
        .warning_level_low[ 0 ]  = { 0 },
        .warning_level_low[ 1 ]  = { 0 },
        .warning_level_low[ 2 ]  = { 0 },
        .warning_level_high[ 0 ] = { 0 },
        .warning_level_high[ 1 ] = { 0 },
        .warning_level_high[ 2 ] = { 0 },
    }
};

/******************************************************
*               Function Definitions
******************************************************/
const imx_functions_t imx_sensor_functions[ IMX_NO_SENSORS ] = {
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = NULL,
    .update =  NULL,
    .arg = SCB_IMX_HOST_S_W_REVISION_103378620,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = NULL,
    .update =  NULL,
    .arg = SCB_IMX_RF_SCAN_123455660,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = NULL,
    .update =  NULL,
    .arg = SCB_IMX_VARIABLE_DATA_IN_2058836870,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = NULL,
    .update =  NULL,
    .arg = SCB_IMX_WIFI_BSSID_173116155,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = NULL,
    .update =  NULL,
    .arg = SCB_IMX_WIFI_CHANNEL_173916172,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = NULL,
    .update =  NULL,
    .arg = SCB_IMX_WIFI_RF_NOISE_1248909411,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = NULL,
    .update =  NULL,
    .arg = SCB_IMX_WIFI_RSSI_101600364,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_ble_device_rssi_levels_2037468041,
    .update =  sample_ble_device_rssi_levels_2037468041,
    .arg = SCB_BLE_DEVICE_RSSI_LEVELS_2037468041,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_co2_equivalent_2088797904,
    .update =  sample_co2_equivalent_2088797904,
    .arg = SCB_CO2_EQUIVALENT_2088797904,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_humidity_342048076,
    .update =  sample_humidity_342048076,
    .arg = SCB_HUMIDITY_342048076,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_mass_concentration_pm_1_0_32791331,
    .update =  sample_mass_concentration_pm_1_0_32791331,
    .arg = SCB_MASS_CONCENTRATION_PM_1_0_32791331,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_mass_concentration_pm_10_0_734215216,
    .update =  sample_mass_concentration_pm_10_0_734215216,
    .arg = SCB_MASS_CONCENTRATION_PM_10_0_734215216,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_mass_concentration_pm_2_5_1698993330,
    .update =  sample_mass_concentration_pm_2_5_1698993330,
    .arg = SCB_MASS_CONCENTRATION_PM_2_5_1698993330,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_mass_concentration_pm_4_0_1858953557,
    .update =  sample_mass_concentration_pm_4_0_1858953557,
    .arg = SCB_MASS_CONCENTRATION_PM_4_0_1858953557,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_number_concentration_pm_0_5_1642774029,
    .update =  sample_number_concentration_pm_0_5_1642774029,
    .arg = SCB_NUMBER_CONCENTRATION_PM_0_5_1642774029,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_number_concentration_pm_1_0_1984590476,
    .update =  sample_number_concentration_pm_1_0_1984590476,
    .arg = SCB_NUMBER_CONCENTRATION_PM_1_0_1984590476,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_number_concentration_pm_10_0_1909326236,
    .update =  sample_number_concentration_pm_10_0_1909326236,
    .arg = SCB_NUMBER_CONCENTRATION_PM_10_0_1909326236,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_number_concentration_pm_2_5_1751774023,
    .update =  sample_number_concentration_pm_2_5_1751774023,
    .arg = SCB_NUMBER_CONCENTRATION_PM_2_5_1751774023,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_number_concentration_pm_4_0_891153645,
    .update =  sample_number_concentration_pm_4_0_891153645,
    .arg = SCB_NUMBER_CONCENTRATION_PM_4_0_891153645,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_particulate_matter_index_1695740845,
    .update =  sample_particulate_matter_index_1695740845,
    .arg = SCB_PARTICULATE_MATTER_INDEX_1695740845,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_temperature_1913614964,
    .update =  sample_temperature_1913614964,
    .arg = SCB_TEMPERATURE_1913614964,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_typical_particle_size_159299661,
    .update =  sample_typical_particle_size_159299661,
    .arg = SCB_TYPICAL_PARTICLE_SIZE_159299661,
},
{
    .load_config_defaults = load_config_defaults_generic_scb,
    .init = init_voc_1189979747,
    .update =  sample_voc_1189979747,
    .arg = SCB_VOC_1189979747,
}
};

/* [] END OF FILE */
